name: testcontainers
on:
 push:
   branches:
     - '**'
jobs:
 build:
   name: Maven Build
   runs-on: ubuntu-latest
   steps:
     - uses: actions/checkout@v5
     - name: Setup Python3
       uses: actions/setup-python@v5
       with:
         python-version: 3.11