name: testcontainers
on:
 push:
   branches:
     - '**'
jobs:
 build:
   runs-on: ubuntu-latest
   steps:
     - uses: actions/checkout@v5
     - name: Set up Python
       uses: actions/setup-python@v5
       with:
         python-version: '3.x'
      - name: Display Python version
        run: python -c "import sys; print(sys.version)"